# 1. Configuração Geral
log.file.level = info
# loopback_users.guest = false

# 2. Configuração de Vhosts
# default_vhost = /

# 3. Configuração de Usuários
# default_user = master
# default_pass = bWFzdGVy

# 4. Configuração de Plugins
management.load_definitions = /etc/rabbitmq/definitions.json

# 5. Configuração de Network
# listeners.tcp.default = 5672
# management.tcp.port = 15672

# 6. Configuração de Cluster
# cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
# cluster_formation.classic_config.nodes.1 = rabbit@node1
# cluster_formation.classic_config.nodes.2 = rabbit@node2
# cluster_formation.classic_config.nodes.3 = rabbit@node3
# cluster_partition_handling = autoheal

# 7. Configuração de TLS (opcional)
# listeners.ssl.default = 5671
# ssl_options.cacertfile = /etc/rabbitmq/ssl/ca_certificate.pem
# ssl_options.certfile = /etc/rabbitmq/ssl/server_certificate.pem
# ssl_options.keyfile = /etc/rabbitmq/ssl/server_key.pem
# ssl_options.verify = verify_peer
# ssl_options.fail_if_no_peer_cert = true
